### ISSUE TITLE
"Uncaught TypeError: Object(...) is not a function" when using 'popup' in month view

### ISSUE THREAD

**Issue by paulhuisman** [jquense/react-big-calendar#1565]
## Versions
React: 16.6.3
React Big Calendar: 0.23.0

## Problem
I'm trying to implement React Big Calendar on my site (using webpack).

The error i'm getting when trying to add React Big Calendar to the dom is:
```
useCallbackRef.js?ec0e:26 Uncaught TypeError: Object(...) is not a function
    at useCallbackRef (useCallbackRef.js?ec0e:26)
    at eval (Overlay.js?dc71:25)
    at updateForwardRef (react-dom.development.js?61bb:14118)
    at beginWork (react-dom.development.js?61bb:15099)
    at performUnitOfWork (react-dom.development.js?61bb:17820)
    at workLoop (react-dom.development.js?61bb:17860)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:199)
    at invokeGuardedCallback (react-dom.development.js?61bb:256)
    at replayUnitOfWork (react-dom.development.js?61bb:1710
```

```
react-dom.development.js?61bb:15749 The above error occurred in the <Overlay> component:
    in div (created by MonthView)
    in MonthView (created by Calendar)
    in div (created by Calendar)
    in Calendar (created by Uncontrolled(Calendar))
    in Uncontrolled(Calendar) (created by ForwardRef)
    in EventCalendar
```

JSX file:

```
        <Calendar
          popup
          selectable
          date={this.state.calendarDate}
          onNavigate={this.handleNavigate}
          onView={this.handleView}
          messages={messages}
          formats={formats} 
          defaultView="week"
          localizer={localizer}
          showMultiDayTimes={true}
          events={this.state.events}
          onSelectEvent={event => window.location.assign('/events/' + event.id)}
          onSelectSlot={this.handleSelect}
          eventPropGetter={this.customEventPropGetter}
          components={{
            event: this.formatEvent,
            toolbar: CalendarToolbarCallback(this.toggleFilters, this.setCalendarDate, this.state.filterIsActive),
            agenda: {
              event: this.formatEventListItem,
            }
          }}
        />
```

The error is occurring during month view and does NOT trigger when i remove `popup` from my component. 

So the problem seems to be contained within `<Overlay>` and the `popup` attribute.

Can anyone help out?

**Comment by paulhuisman** [comment]
Still having this issue :( Does anyone have any idea?

**Comment by Alejando** [comment]
Hi @paulhuisman, I have the same issue, but I fixed it using the version "0.22.0" ;)

**Comment by paulhuisman** [comment]
@Alejando Thanks for your message. Any important feature differences between 0.22 and 0.23? :)

**Comment by paulhuisman** [comment]
Tried doing this but unfortunately it did not solve the issue.

**Comment by paulhuisman** [comment]
@Alejando Unfortunately downgrading to 0.22.0 didn't help me.

**Comment by michalak111** [comment]
@paulhuisman could you provide some demo in codesandbox.io with this I'm sure will be easier to find root cause of this bug

**Comment by cutterbl** [comment]
I have `popup` working just fine with 0.23.0 in this [CodeSandbox Example](https://codesandbox.io/embed/rbc-view-control-old-vbsbi?fontsize=14&hidenavigation=1&theme=dark). Maybe it's a build issue? Conflicting react-overlays library somewhere?

**Comment by cutterbl** [comment]
To elaborate on my previous statement: maybe it's an issue with _your_ build, and you may have a `react-overlays` conflict in _your_ code.

**Comment by paulhuisman** [comment]
Hi @cutterbl  thanks for your response.

It's indeed weird because it's used to work at one time. I guess something's changes in my package.json however i have a hard time finding out what causes it.

I tried removing `react-overlays` from node_modules and running `npm i` again. No luck.. which version of react-overlays are you running in your .lock file?

**Comment by paulhuisman** [comment]
You're correct, its an error in my build. Closing this.

**Comment by nol13** [comment]
@paulhuisman what did you need to change in your build? seeing similar issue
